from . import tipo_trafico
from . import res_config_settings
from . import res_partner
from . import parentesco
from . import reparto_tipo
from . import reparto
from . import tipo_construccion
from . import tipo_astillero
from . import puerto_registro
from . import puerto
from . import agencia_naviera
from . import agencia_puerto
from . import armador
from . import owner_matricula
from . import matricula_agencia
from . import matricula_armador
from . import propietario
from . import departamento
from . import cargo
from . import sigmap_updated_by
from . import tipo_fletamento
from . import sigmap_documento_tipo
from . import sigmap_periodo
from . import sigmap_resolucion
from . import sigmap_secuencia_tipo
from . import sigmap_documento_secuencia_tipo
from . import jurisdiccion
from . import sigmap_convenio
from . import sociedad_clasificadora
from . import persona_tipo_rango
from . import ir_ui_menu
from . import ir_actions_report
