{
    'name': "Personal marítimo",
    'summary': "Información de personal marítimo",
    'description': """
    TODO: add description
    """,
    'author': "DIRNEA",
    'website': "https://www.dirnea.org/",
    'category': 'mar',
    'version': '1.0',
    'depends': [
        'mail',
        'account',
        'web',
        'tipo_centro',
        'base_sigmap',
        'nave',
        ],
    'data': [
        'data/categoria.materia.csv',
        'data/materia.omi.csv',
        'data/personal.maritimo.clasificacion.csv',
        'data/personal.maritimo.clase.persona.csv',
        'data/personal.maritimo.catalogo.jerarquia.csv',
        'data/personal.maritimo.catalogo.tipo.curso.csv',
        'data/personal.maritimo.catalogo.curso.csv',
        'data/personal.maritimo.catalogo.curso.line.csv',
        'data/personal.maritimo.catalogo.jerarquia.curso.csv',
        'data/personal.maritimo.catalogo.limitacion.csv',
        'data/tipo.infraccion.csv',
        'data/tipo.sancion.csv',
        'data/personal.maritimo.curso.tipo.formacion.csv',
        'data/permar.permiso.provisional.embarque.tipo.csv',
        'data/sequence.xml',
        'views/res_config_settings.xml',
        'data/default_settings.xml',
        'views/materia_omi_views.xml',
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'views/res_partner_views.xml',
        'views/personal_maritimo_views.xml',
        #'views/personal_maritimo_simple_views.xml',
        'views/ficha_medica_views.xml',
        'views/jerarquia.xml',
        'views/curso_views.xml',
        'views/limitacion_views.xml',
        'views/linea_jerarquia.xml',
        'views/personal_maritimo_curso_views.xml',
        'views/personal_maritimo_sancion_views.xml',
        'views/personal_maritimo_clase_persona_views.xml',
        'views/personal_maritimo_foto_firma_views.xml',
        'views/personal_maritimo_menuitem.xml',
        'report/personal_maritimo_templates.xml'
    ],
}
