{
    'name': "Documentos de personal marítimo",
    'summary': "Documentos asignados a gente de mar",
    'description': """
    TODO: add description
    """,
    'author': "DIRNEA",
    'website': "https://www.dirnea.org/",
    'category': 'personalmar',
    'version': '1.0',
    'depends': [
        'mail',
        'web',
        'tramite',
        'personal_maritimo',
        'control_suministro',
        ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'views/refrendo_titulo_views.xml',
        'views/certificado_medico_views.xml',
        'views/reconocimiento.xml',
        'views/reconocimiento_certificado_medico_views.xml',
        'views/documento_evaluacion_views.xml',
        'views/evaluacion_competencia_views.xml',
        'views/convalidacion_competencia_views.xml',
        'views/certificado_competencia_views.xml',
        'views/certificado_suficiencia_views.xml',
        'views/permiso_provisional_embarque_views.xml',
        'views/dispensa_views.xml',
        'views/dotacion_views.xml',
        'views/tipo_trafico_views.xml',
        'views/matricula_control_impresion_views.xml',
        'views/carnet_views.xml',
        'views/libretin_views.xml',
        'views/persona_autoridad_views.xml',
        'views/sumilla_usuario_views.xml',
        'views/tramite_documento.xml',
        'views/menuitem.xml',
        'wizard/documento_numero_formato_views.xml',
        'wizard/sale_order_cancel_views.xml',
        'wizard/documento_matricula_wizard_views.xml',
        'data/sequence.xml',
        'data/matricula.motivo.csv',
        'reports/custom_report_footer_templates.xml',
        'reports/base_titulo_report_templates.xml',
        'reports/report_paperformat.xml',
        'reports/certificado_medico_report_templates.xml',
        'reports/certificado_competencia_report_templates.xml',
        'reports/certificado_suficiencia_report_templates.xml',
        'reports/permiso_provisional_embarque_report_templates.xml',
        'reports/dispensa_report_templates.xml',
        'reports/dotacion_report_templates.xml',
        'reports/evaluacion_competencia_report_templates.xml',
        'reports/convalidacion_competencia_report_templates.xml',
        'reports/refrendo_titulo_report_templates.xml',
        'reports/carnet_report_templates.xml',
        'reports/libretin_report_templates.xml',
        'reports/reconocimiento_report_templates.xml',
        'reports/custom_report_header_templates.xml',
        'data/tramite.documento.csv',
    ],
    'css': [
        'static/src/css/styles.css',
    ],
}
