from . import persona_autoridad
from . import base_documento
from . import base_documento_refrendo
from . import base_documento_matricula
from . import refrendo_titulo
from . import refrendo_certificado_medico
from . import reconocimiento
from . import reconocimiento_certificado_medico
from . import control_impresion
from . import carnet
from . import libretin
from . import documento_evaluacion
from . import evaluacion_competencia
from . import convalidacion_competencia
from . import certificado_competencia
from . import certificado_suficiencia
from . import permiso_provisional_embarque
from . import dispensa
from . import dotacion
from . import tramite
