from . import nave_grupo
from . import nave_tipo
from . import nave_servicio
from . import nave_origen
from . import nave_clase_matricula
from . import nave_zona
from . import nave_tipo_propulsion
from . import nave_casco_material
from . import nave_estado
from . import nave
from . import nave_foto
from . import nave_constructor
from . import nave_canal_frecuencia
from . import nave_dispositivo
from . import nave_motor
from . import nave_owner
from . import nave_agencia
from . import nave_propietario
from . import nave_armador
from . import sigmap_agencia
from . import sigmap_propietario
from . import sigmap_armador
from . import nave_matricula_bitacora
from . import nave_domain_regla
from . import res_config_settings
