from . import res_config_settings
from . import jerarquia
from . import personal_maritimo
from . import curso
from . import limitacion
from . import curso_persona
from . import sancion
from . import materia_omi
from . import foto_firma
from . import certificado_medico
from . import tipo_permiso_embarque