{
    'name': "Trámites",
    'summary': "Generación trámites",
    'description': """
    TODO: add description
    """,
    'author': "DIRNEA",
    'website': "https://www.dirnea.org/",
    'category': 'mar',
    'version': '1.0',
    'depends': [
        'mail',
        'web',
        'sale_management',
        'account',
        'product',
        'base_sigmap',
        'personal_maritimo',
        'nave',
        'citacion',
        'usuarios'
        ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/tramite.tarifario.csv',
        'data/tramite.documento.csv',
        #'data/tramite_documento_nave.xml',
        'data/mail_templates_tramite.xml',
        'data/mail_templates_documento_emitido.xml',
        'data/mail_templates_sale_order_tramite.xml',
        'data/product.template.csv',
        'data/rubro.tarifa.csv',
        'data/tramite.documento.requisito.csv',
        'views/documento.xml',
        'views/res_config_settings.xml',
        'data/default_settings.xml',
        'views/sale_order_views.xml',
        'views/tarifario.xml',
        'views/tramite.xml',
        'views/documento_emitido.xml',
        'wizard/wizard_tramite_tarifario_rubro_update_views.xml',
        'wizard/motivo_rechazo_documento_wizard_views.xml',
        'wizard/motivo_invalidar_documento_wizard_views.xml',
        'wizard/firmar_documento_views.xml',
        'views/solicitud_menuitem.xml',
    ],
}
